### PR TITLE
Enable disabling bogus query suffix

### PR DESCRIPTION
**Pull request by pchaigno**
Without this change, calling `harvest("java", "")` still adds a bogus query suffix because `!""` is interpreted as true.

### CODE REVIEW

**Comment by Alhadis** [comment]
Sorry, you'll need to fix the merge conflict...

**Comment by pchaigno** [comment]
Done.

**Comment by Alhadis** [comment]
Merci!

**Comment by pchaigno** [comment]
Beware white spaces around punctuation marks in French: "Merci !" (or how to spot a French person writing English).

You're welcome!

**Comment by Alhadis** [comment]
I prefer tabs, so for me it'd be more like `Merci\t!`.. 😅👌

(I always did wonder why French puts spaces before an exclamation mark...)

**Comment by pchaigno** [comment]
Whoa! That actually got displayed as a tab in my mails!

It's actually supposed to be an *espace fine insécable* or small non-breaking space.

**Pull request merged**
