### PR TITLE
README instructions to preserve directory hierarchy

### PR DESCRIPTION
**Pull request by pchaigno**
Additional instructions in README to download files with their original directory hierarchy.

Not sure if I should use `wget -q` or `wget` here. `wget` is faster, but it gives the impression nothing is going on :-/

### CODE REVIEW

**Comment by Alhadis** [comment]
Tabs, please. 😉 You know I can't stand spaces.

Also, shouldn't `wget -x` be good enough? 🤔 Granted, you wind up with a directory structure like this...

~~~console
$ tree
├── raw.githubusercontent.com
│   ├── Knight-H
│   │   └── RobotUI
│   │       └── 0eeccb86e6519c6c4390de522a36efe748806d06
│   │           └── angular-src
│   │               └── src
│   │                   └── assets
│   │                       └── …
~~~

... but that's admittedly simpler and less collision-proof (since the hashed directory ensures two files indexed from the same repository don't overwrite each other).

**Comment by pchaigno** [comment]
> Also, shouldn't wget -x be good enough?

Arg! Yes, I'll document that instead.

> since the hashed directory ensures two files indexed from the same repository don't overwrite each other

That can happen??

**Comment by Alhadis** [comment]
> That can happen??

It's theoretically possible that a repository has two disconnected branches with a file of the same path (but differing in content). Though it's more of an edge case than anything serious.

**Comment by pchaigno** [comment]
Isn't only the primary branch indexed? Or would that happen only if the primary branch was changed?

**Comment by Alhadis** [comment]
> Isn't only the primary branch indexed?

Admittedly, I don't know how GitHub works concerning the indexing of alternate branches. But it wouldn't make sense for certain files to be exempt from public search results simply because they're isolated in a separate branch. E.g., [`dspinellis/unix-history-repo`](https://github.com/dspinellis/unix-history-repo) contains dozens of branches for each different release of Unix, meaning most of the files contained therein would be "undiscoverable" if only the main branch was indexed.

**Comment by pchaigno** [comment]
Branch updated with the `-x` option. Much better :-)

**Review by Alhadis — APPROVED** [review]

**Pull request merged**
